---
apiVersion: v1
offerings:
  - name: Retrieval_Augmented_Generation_Pattern_dev
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 6068c87c-ed4b-4427-be22-d7ac65fa2a8e
    variations:
      - name: basic
        mark_ready: true
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
